### ISSUE TITLE
Contacting Motoharu

### ISSUE THREAD

**Issue by diego-rbb-93** [motoharu-gosuto/psvcmd56#2]
Hi!

I wanted to leave you a message but i didnt know how. I come from VideoGaming Preservation Collective group, we are a group of volunteers coming from different preservationg groups like Redump, No-Intro, TOSEC...

We need your help, we've being doing heavy research on PS Vita game cartridge preservation and we wanted to discuss with you some interesting info about your tool, PsVitaGamesSd, which we are using as leading tool for our project.

Please, if you are able, contact us here, we have some mates that would be really excited to talk with you about your work:

https://discord.gg/Drjcnyp

Yifan Lu is in too, as i said, we are working hard to determine how to make a correct preservation over these carts and its being a difficult job, hope you can help us!

**Comment by motoharu-gosuto** [comment]
@diego-rbb-93
Wow. I did not expect to get a message here. I will try to reach you on discord.
